stages:
  data_ingestion:
    cmd: python src/data/ingestion.py
    deps:
      - src/data/ingestion.py
      - src/entity/config_entity.py
      - src/entity/artifact_entity.py
    outs:
      - data/external
