stages:
  data_ingestion:
    cmd: python app_src/data/ingestion.py
    deps:
      - app_src/data/ingestion.py
      - app_src/entity/config_entity.py
      - app_src/entity/artifact_entity.py
    outs:
      - data/external

  data_cleaning:
    cmd: python app_src/data/cleaning.py
    deps:
      - app_src/data/cleaning.py
      - app_src/entity/config_entity.py
      - app_src/entity/artifact_entity.py
    outs:
      - data/raw/Ml_books.csv
      - data/raw/all_papers.csv

  build_features:
    cmd: python app_src/data/build_features.py
    deps:
      - app_src/data/build_features.py
      - app_src/entity/config_entity.py
      - app_src/entity/artifact_entity.py
      - data/raw/Ml_books.csv
      - data/raw/all_papers.csv
    outs:
      - data/interim/modified_books.csv
      - data/interim/modified_papers.csv
  
  sentence_transformer_model_trainer:
    cmd: python app_src/models/model2/train.py
    deps:
        - app_src/models/model2/model.py
        - app_src/entity/config_entity.py
        - app_src/entity/artifact_entity.py
        - app_src/data/build_features.py
        - data/interim/modified_books.csv
        - data/interim/modified_papers.csv
    outs:
        - data/processed/matrices





  # model_trainer:
  #   cmd: python app_src/models/model1/model.py
  #   deps:
  #     - app_src/models/model1/model.py
  #     - app_src/entity/config_entity.py
  #     - app_src/entity/artifact_entity.py
  #     - app_src/data/build_features.py
  #     - data/interim/modified_books.csv
  #     - data/interim/modified_papers.csv
  #   outs:
  #     - data/processed/models
  #     - data/processed/matrices


  # prediction:
  #   cmd: python app_src/models/model1/predict.py "machine learning" > data/processed/predictions.json
  #   deps:
  #     - app_src/models/model1/predict.py
  #     - app_src/models/model1/model.py
  #     - app_src/entity/config_entity.py
  #     - app_src/entity/artifact_entity.py
  #     - data/processed/models
  #     - data/processed/matrices
  #     - data/interim/modified_books.csv
  #     - data/interim/modified_papers.csv
  #   outs:
  #     - data/processed/predictions.json


 
   
