stages:
  data_ingestion:
    cmd: python src/data/ingestion.py
    deps:
      - src/data/ingestion.py
      - src/entity/config_entity.py
      - src/entity/artifact_entity.py
    outs:
      - data/external

  data_cleaning:
    cmd: python src/data/cleaning.py
    deps:
      - src/data/cleaning.py
      - src/entity/config_entity.py
      - src/entity/artifact_entity.py

    outs:
      - data/raw/Ml_books.csv
      - data/raw/all_papers.csv

  build_features:
    cmd: python src/data/build_features.py
    deps:
      - src/data/build_features.py
      - src/entity/config_entity.py
      - src/entity/artifact_entity.py
      - data/raw/Ml_books.csv
      - data/raw/all_papers.csv
    outs:
      - data/interim/modified_books.csv
      - data/interim/modified_papers.csv

  model_trainer:
    cmd: python src/models/model1/model.py
    deps:
      - src/models/model1/model.py
      - src/entity/config_entity.py
      - src/entity/artifact_entity.py
      - src/data/build_features.py
      - data/interim/modified_books.csv
      - data/interim/modified_papers.csv
    outs:
      - data/processed/models
      - data/processed/matrices
      - data/processed/final

  prediction:
    cmd: python src/models/model1/predict.py "machine learning" > data/processed/predictions.json
    deps:
      - src/models/model1/predict.py
      - data/processed/models
      - data/processed/matrices
      - data/processed/final
      - data/interim/modified_books.csv
      - data/interim/modified_papers.csv
    outs:
      - data/processed/predictions.json
